package com.bolivar.comunes.personas_trabajadores_arl.consultartrabajadores.services;

import com.bolivar.comunes.personas_trabajadores_arl.consultartrabajadores.models.ConsultarTrabajadoresRequest;
import com.bolivar.comunes.personas_trabajadores_arl.consultartrabajadores.models.ConsultarTrabajadoresResponse;

public interface ConsultarTrabajadoresService {
	ConsultarTrabajadoresResponse consultarTrabajadores(ConsultarTrabajadoresRequest peticion);
}
