package com.bolivar.comunes.personas_trabajadores_arl.consultarafiliaciontrabajador.services;

import com.bolivar.comunes.personas_trabajadores_arl.consultarafiliaciontrabajador.models.ConsultarAfiliacionTrabajadorRequest;
import com.bolivar.comunes.personas_trabajadores_arl.consultarafiliaciontrabajador.models.ConsultarAfiliacionTrabajadorResponse;

public interface ConsultarAfiliacionTrabajadorService {
	public ConsultarAfiliacionTrabajadorResponse consultaAfiliacionTrabajador(
			ConsultarAfiliacionTrabajadorRequest peticion);
}
